"""Agregar tabla sesiones activas

Revision ID: 07708f886754
Revises: 2442ae6fc73e
Create Date: 2025-05-28 21:05:09.044131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07708f886754'
down_revision = '2442ae6fc73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_activas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesiones_activas')
    # ### end Alembic commands ###
