"""Agrega campo ultima_actividad a sesiones_activas

Revision ID: 0d82d5c41ed8
Revises: 77867c0a49d1
Create Date: 2025-06-22 20:33:12.154527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d82d5c41ed8'
down_revision = '77867c0a49d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_actividad', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.drop_column('ultima_actividad')

    # ### end Alembic commands ###
