"""Actualizar modelo Historial

Revision ID: 2442ae6fc73e
Revises: 77c4d5c00335
Create Date: 2025-05-27 19:33:23.767634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2442ae6fc73e'
down_revision = '77c4d5c00335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_historial_ticket_id', 'tickets', ['ticket_id'], ['id'])
        batch_op.create_foreign_key('fk_historial_usuario_id', 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
