"""Agrega campo email a clientes

Revision ID: 4ab04120fcdf
Revises: bbf9bcdbf9af
Create Date: 2025-06-06 17:04:12.465332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab04120fcdf'
down_revision = 'bbf9bcdbf9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
