"""Agregar relación asignado_id a Ticket

Revision ID: 5a23f7aeaf17
Revises: ceac3ea424b6
Create Date: 2025-05-27 17:23:15.951290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a23f7aeaf17'
down_revision = 'ceac3ea424b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_asignado_id', 'usuarios', ['asignado_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_asignado_id_usuarios', type_='foreignkey')
        batch_op.drop_column('asignado_id')
