"""Add de_turno to Usuario

Revision ID: 5e84f90f2992
Revises: 8b7978689243
Create Date: 2025-05-29 09:09:48.678508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e84f90f2992'
down_revision = '8b7978689243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('de_turno', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('de_turno')

    # ### end Alembic commands ###
