"""Agregar modelo Ticket

Revision ID: 62849db9439c
Revises: 7d3fa48d3a53
Create Date: 2025-05-27 15:02:43.079605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62849db9439c'
down_revision = '7d3fa48d3a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('medio', sa.String(length=50), nullable=True),
    sa.Column('pid', sa.String(length=50), nullable=True),
    sa.Column('asunto', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('sede', sa.String(length=100), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('asignado', sa.String(length=100), nullable=True),
    sa.Column('actualizacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
