"""Agregar campo apellido a Usuario

Revision ID: 77c4d5c00335
Revises: 5a23f7aeaf17
Create Date: 2025-05-27 17:32:14.366536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c4d5c00335'
down_revision = '5a23f7aeaf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
