"""add nota to clientes

Revision ID: 8f1029b7dee8
Revises: 0d82d5c41ed8
Create Date: 2025-06-30 17:07:04.389903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1029b7dee8'
down_revision = '0d82d5c41ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('nota')

    # ### end Alembic commands ###
