"""Relacionar cliente y usuario con ticket

Revision ID: 9d7081d4fc09
Revises: c527baa400ab
Create Date: 2025-05-27 15:54:50.411813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7081d4fc09'
down_revision = 'c527baa400ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('usuarios',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('usuario', sa.String(length=80), nullable=False),
    #sa.Column('password_hash', sa.String(length=128), nullable=False),
    #sa.Column('nombre', sa.String(length=100), nullable=True),
    #sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('usuario')
    #)
    #op.drop_table('usuarios')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_tickets_cliente_id',
            'clientes',
            ['cliente_id'],
            ['id']
        )

        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_tickets_usuario_id',
            'usuarios',
            ['usuario_id'],
            ['id']
        )
            
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asignado_id')
        batch_op.drop_column('cliente_id')

    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.drop_table('usuarios')
    # ### end Alembic commands ###
