"""elimino campo asignado en clase Ticket

Revision ID: ceac3ea424b6
Revises: 8d2b82334bd0
Create Date: 2025-05-27 17:17:09.255657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac3ea424b6'
down_revision = '8d2b82334bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('asignado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignado', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
